cc_library(
    name = 'base_mysql',
    srcs = [
        'base_mysql.cpp',
    ],
    incs = [
        '/usr/include/mysql',
    ],
    deps = [
        '#pthread',
        '#z',
        '#m',
        '#dl',
        '#mysqlclient',
    ]
)
